id = "prolog"
name = "prolog"
version = "0.0.2"
schema_version = 1
authors = [
	"Piefayth <piefayth@gmail.com>",
	"Gaspartcho <g.deremble@laposte.net>",
]

description = "tree-sitter-prolog integration for zed"
repository = "https://github.com/piefayth/zed-prolog"

[grammars.prolog]
repository = "https://codeberg.org/foxy/tree-sitter-prolog"
commit = "39d5e4e89f336b3bbf245f6fae18473b2e8c88a5"
path = "grammars/prolog"

[language_servers.prolog-lsp]
name = "Prolog LSP support"
languages = ["Prolog"]
